version: '3.3'
services:
  cradle:
    build: .
    volumes:
    - ./docker/config-docker-compose.js:/var/www/html/cradle/public_html/config.js
    - ./public_html:/var/www/html/cradle/public_html
    - ./vendor:/var/www/html/cradle/vendor
    ports:
      - 8087:80
